config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  post 'tasks/set_state_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/state.rb
class State < ApplicationRecord
    validates :code, presence: true, uniqueness: {case_sensitive: false }

    @@state_ready = State.find_by(code: "READY")
    @@state_not_ready = State.find_by(code: "NOT READY")

    def State.ready
        @@state_ready
    end

    def State.not_ready
        @@state_not_ready
    end
end

app/models/task.rb
class Task < ApplicationRecord
    validates :description, presence: true, uniqueness: {case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_state, only: [:show, :edit, :set_state_task, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.state_id = State.find_by({code: "NOT READY"}).id
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Tarea creada exitosamente' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def set_state_task
    current_state = State.find(@task.state_id).code
    new_state_id = current_state == "READY" ? State.not_ready.id : State.ready.id
    @task.state_id = new_state_id
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Tarea actualizada exitosamente' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Tarea eliminada exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :state_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label "Descripción" %>
      <%= form.text_field :description %>
    </div>
  
    <div class="actions">
      <%= form.submit  "Agregar Tarea"%>
    </div>
  <% end %>

app/views/tasks/_table.html.erb
<h1><%=title%></h1>

<%if tasks.count != 0%>
<table>
  <thead>
    <tr>
      <th>Descripción</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% tasks.each do |task| %>
      <tr id="task_<%=task.id%>">
        <td><%= task.description %></td>
        <td><%= button_to btn_update, {action: :set_state_task, id: task.id} %></td>
        <td><%= button_to "Eliminar", task, method: :delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
<h3>
No hay <%= title.downcase%>
</h3>
<%end%>

app/views/tasks/create.html.erb
<h1>Task#create</h1>
<p>Find me in app/views/task/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Task#destroy</h1>
<p>Find me in app/views/task/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Task#edit</h1>
<p>Find me in app/views/task/edit.html.erb</p>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row">
        <div class="col-12">
            <%= render 'table', 
                title: "Tareas Pendientes", 
                tasks:  @tasks.where("state_id = ?", State.find_by(code: "NOT READY")),
                btn_update: "Lista?" %>
        </div>
        <div class="col-12">
            <%= render 'table', 
                title: "Tareas Listas", 
                tasks:  @tasks.where("state_id = ?", State.find_by(code: "READY")),
                btn_update: "Oops..." %>
        </div>
    </div>
</div>

<br>

<%= button_to " Nueva Tarea", new_task_path, method: "get" %>

app/views/tasks/new.html.erb
<h1>Nueva Tarea</h1>

<%= render 'form', task: @task %>

<%= link_to 'Volver', tasks_path %>

app/views/tasks/update.html.erb
<h1>Task#update</h1>
<p>Find me in app/views/task/update.html.erb</p>